// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types.ts';

const SUPABASE_URL = "https://tgtoykxksohyalgifcdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRndG95a3hrc29oeWFsZ2lmY2RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzA3OTQsImV4cCI6MjA2NzU0Njc5NH0.lZLZ2WRdrrvTEQQWI9uZsWb6qOw2R92B3WZGZKEdlf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});